// Options for my select component
export const categoryOptions = [
  { value: "web dev", label: "Web Development" },
  { value: "app dev", label: "Mobile App Development" },
  { value: "cyber security", label: "Cyber Security" },
  { value: "programming lang", label: "Programming Language" },
  { value: "frontend", label: "Front end Development" },
  { value: "back-end", label: "Backend Web Development" },
  { value: "dbms", label: "Database Management" },
  { value: "iot", label: "IoT" },
  { value: "ml/ai", label: "ML/AI" },
  { value: "cloud computing", label: "Cloud Computing" },
  { value: "robotics", label: "Robotics" },
  { value: "embedded systems", label: "Embedded Systems" },
  { value: "computer architecture", label: "Computer Architecture" },
  { value: "computer vision", label: "Computer Vision" },
  { value: "distributed computing", label: "Distributed Computing" },
  { value: "data science", label: "Data Science" },
  { value: "computer graphics", label: "Computer Graphics" },
  { value: "quantam computing", label: "Quantam Computing" },
];
